### PR TITLE
Add types for get_client_ip parameters

### PR DESCRIPTION
**Pull request by federicobond**

### CODE REVIEW

**Comment by un33k** [comment]
@federicobond please kindly change the PR against the CI branch.  Thx

**Comment by federicobond** [comment]
Hi @un33k! Like this?

**Comment by federicobond** [comment]
Thank you!

**Comment by un33k** [comment]
It is pushed to pypi at 6.0.4.  Thanks again.

**Comment by federicobond** [comment]
@un33k could it be that the package does not contain the py.typed file when installed via pip? This is preventing mypy from recognizing the types.

**Comment by un33k** [comment]
I'll push up the PRs as they arrive. Thx

**Comment by federicobond** [comment]
I'm sorry, I did not understand what you said.

**Comment by un33k** [comment]
I meant:  community enhancement PRs are welcomed whether it'd be for setup.py or anything else.

**Pull request merged**
